#!/usr/bin/env bash
set -ex
cd $(dirname $0)

which wget \
	&& wget -O boost.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.bz2/download \
	|| curl -L -o boost.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.bz2/download
tar xf boost.tar.bz2
cd boost_1_62_0/
./bootstrap.sh
./bjam toolset=gcc release link=shared install cxxflags=-std=c++14 --prefix=../boost --with-coroutine --with-system
mv ../boost/lib ../boost/release
./bjam toolset=gcc debug link=shared install cxxflags=-std=c++14 --prefix=../boost --with-coroutine --with-system
mv ../boost/lib ../boost/debug
